version: '3.8'

services:
  talent-of-time:
    image: ${DOCKERHUB_USERNAME}/talent-of-time:${IMAGE_TAG}
    container_name: talent-of-time
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
      - REDIS_SERVER_HOST=${REDIS_SERVER_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./logs:/var/log/spring
    restart: unless-stopped

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345"
    environment:
      - ALLOY_ENV=prod
      # .env 파일에 작성해둔 HOSTNAME(예: spring-server-1)을 주입
      - HOSTNAME=${HOSTNAME}
      - LOKI_IP=${REDIS_SERVER_HOST}
    volumes:
      - ./logs:/var/log/spring
      - ./infra/config.alloy:/etc/alloy/config.alloy:ro
    restart: unless-stopped
    depends_on:
      - talent-of-time
