spring:
  config:
    activate:
      on-profile: prod

  threads:
    virtual:
      enabled: false

  data:
    redis:
      host: ${REDIS_SERVER_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      auto-commit: false
      maximum-pool-size: 3        # master(3개) + slave(3개) 로 최대 db 에는 총 10개 연결
      minimum-idle: 3             # max와 동일하게 맞춰서 불필요한 커넥션 생성/삭제 비용 제거
      data-source-properties:
        cachePrepStmts: true          # 클라이언트 측 Prepared Statement 캐싱 활성화
        prepStmtCacheSize: 250        # 커넥션당 캐싱할 Prepared Statement 수
        prepStmtCacheSqlLimit: 2048   # 캐싱할 SQL 문의 최대 길이
        useServerPrepStmts: true      # MySQL 서버 측 Prepared Statement 사용 (서버에서 실행 계획을 캐싱)

  sql:
    init:
      mode: never

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    database: mysql
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        format_sql: false
        query:
          in_clause_parameter_padding: true

  flyway:
    enabled: true

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email

jwt:
  secret: ${JWT_SECRET}

token:
  access:
    storage-key-prefix: "accessToken:"
    expire-time: 2h
  refresh:
    storage-key-prefix: "refreshToken:"
    expire-time: 14d

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: never

app:
  cookie:
    secure: true

gemini:
  api:
    key: ${GEMINI_API_KEY}
